#!/usr/bin/env bash

#for prec in "-DENABLE_SINGLE_PRECISION=OFF -DENABLE_DOUBLE_PRECISION=ON" "-DENABLE_SINGLE_PRECISION=ON -DENABLE_DOUBLE_PRECISION=OFF"
for prec in "-DENABLE_SINGLE_PRECISION=OFF -DENABLE_DOUBLE_PRECISION=ON"
do
  rm -rf $BUILD
  OPTIONS="-S $ECTRANS_ROOT -B $BUILD"
  cmake $OPTIONS $prec
  cmake --build $BUILD
  cmake --install $BUILD
done
